### ISSUE TITLE
atlas nodes

### ISSUE THREAD

**Issue by Blemming** [FloKaemmerer/dynamic-atlas#53]
How did you generate the atlasNode.json ? it is probably worth trying to automate it if you made it manually otherwise its a lot of work every patchnotes ( soon )

**Comment by FloKaemmerer** [comment]
It's a semi automatic process.

The AtlasNodes are based off of [https://poedb.tw/us/api/AtlasNode](url) (Which is Datamined from the Gamefiles afaik)

I have a little Spring Service that I run locally with a postgres DB which holds the Data.
I can import the json from poedb and the Service updates the Nodes accordingly.

further I can set Nodes to active/inactive, add Div Cards and update the values for openess, Backtrack Factor etc.

Than I can request the complete Json from the Service and copy/paste it into the this project.

As long as they don't add maps that where out for more then three leagues, everything should already be in the DB.
If the Data isn't present we will have to set the values (Div cards, Openness etc.) for them. But I think we I'm missing something like 10 maps at most.

But since the actuall Data comes from the gamefiles, the update can only happen shortly before launch :-/

**Comment by FloKaemmerer** [comment]
Just Checked the Patchnotes for Maps that are Missing, found 11 (maybe there are a few more missing in the DB than I expected XD):

Arena
Basilica
Glacier
Lava Chamber
Mud Geyser
Palace
Pen
Reef
Summit
Vault
Waterways

I will at them as inactive skeletons to the Json, to be able to edit their values prior to the patch.

**Comment by FloKaemmerer** [comment]
I added the missing nodes #54 

We will have for the Datamind real values for ID, Links, tier, and coordinates.

**Comment by Blemming** [comment]
I found https://snosme.github.io/poe-dat-viewer/ , if you navigate to data/atlasnodes.dat64 you can click export data on top right it should download a JSON not sure if that helps you out a bit. Obviously this only works when the new patch is released by GGG

**Comment by FloKaemmerer** [comment]
I know that page and used it to get the ingame assets, like the map base, symbols, background and so on.

**Comment by FloKaemmerer** [comment]
Successfully Updated the Atlas for 3.22! :-D

**Comment by FloKaemmerer** [comment]
Since everything seem to be fine for 3.22 I'm going to close this one.
